# Generated by Django 4.0.5 on 2022-07-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
