# Generated by Django 4.0.5 on 2022-08-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0002_rename_cliente_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='status',
            field=models.CharField(choices=[('M', 'Mesalidade'), ('A', 'Anuidade'), ('S', 'Sem Contrato')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=models.IntegerField(unique=True),
        ),
    ]
